name: SSH2Action

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

#  schedule:
#    - cron: 30 23 * * *
#  release:
#    types: published
#  watch:
#    types: started

env:
  UPLOAD_FILES: false
  TZ: Asia/Shanghai
  TAG_BRANCH: main
  TAG_NAME: TAG_TEST
  RELEASE_NAME: Armbian_Buster

jobs:
  ssh2action:
    runs-on: ubuntu-18.04
    if: github.event.sender.id == '54447830' || github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        echo ${{ github.event.repository.owner.id }}
        echo ${{ github.event.sender.id }}

    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v1.2.3
      with:          
        token: ${{ secrets.PAT }}
        repository: ${{ github.repository }}
        retain_days: 30
        keep_minimum_runs: 1
          

