# File: .github/workflows/repo-sync.yml
# Need add secrets.PAT

name: repo-sync-P3TERX
on:
  workflow_dispatch:
 # schedule:
   # - cron: '0 1 * * 1'
    # UTC时区，比我们东八区早，上面示例为：每周一9点。
    
env:
  TZ: Asia/Shanghai
  TOCURRENT: false
  TOREMOTE: true
  SOUECE_OWNER: P3TERX
  DEST_OWNER: Namestars
  SYNCTAGS: true
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.sender.id == '54447830' || github.event.repository.owner.id == github.event.sender.id
    
    name: Sync ${{ matrix.list }}
    strategy:
      fail-fast: false
      max-parallel: 10
      matrix:
        list: [Actions-OpenWrt,GeoLite.mmdb,warp.sh,wireguard-go-builder,Aria2-Pro-Docker,Aria2-Pro-Core,ariang,aria2.sh,aria2.conf,ca-certificates.crt]
        # Not updated repos
        # [Gitpod-OpenWrt,openwrt-list,cloudflare-ddns-script,openwrt-build-env,ssh2actions,SSH_Key_Installer,termux.sh,goindex_backup]
        
    steps:  
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: repo-sync-current      
        uses: repo-sync/github-sync@v2
        if: env.TOCURRENT == 'true'
        with:
          source_repo: "https://github.com/template/template.git"
          source_branch: "master"
          destination_branch: "master"
          sync_tags: "false"
          github_token: ${{ secrets.PAT }}
          
      - name: git-sync-remote-branch
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true'
        with:
          source_repo: "${{ env.SOUECE_OWNER }}/${{ matrix.list }}"
          source_branch: "refs/remotes/source/*"
          #source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          destination_branch: "refs/heads/*"
          #destination_branch: "refs/tags/*"          
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: git-sync-remote-tags
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && env.SYNCTAGS == 'true'
        with:
          source_repo: "${{ env.SOUECE_OWNER }}/${{ matrix.list }}"
          #source_branch: "refs/remotes/source/*"
          source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          #destination_branch: "refs/heads/*"
          destination_branch: "refs/tags/*"          
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:          
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 1
          

