# File: .github/workflows/Auto_sync_remote_repo_Template.yml
# Need add secrets.PAT

name: repo-sync-zerotier-official
on:
  workflow_dispatch:
 # schedule:
   # - cron: '0 1 * * 1'
    # UTC时区，比我们东八区早，上面示例为：每周一9点。
    
env:
  TZ: Asia/Shanghai
  TOCURRENT: false
  TOREMOTE: true
  SYNCTAGS: true
  SOURCE_OWNER: zerotier
  DEST_OWNER: Namestars
  KAAASS: true
  
jobs:
  sync-current_remote-repo:
    runs-on: ubuntu-latest
    if: github.event.sender.id == '54447830' || github.event.repository.owner.id == github.event.sender.id
    
    name: Sync ${{ matrix.list }}
    strategy:
      fail-fast: false
      matrix:
        list: [ZeroTierOne,docs,install.zerotier.com,DesktopUI]
        
    steps:  
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: repo-sync-current      
        uses: repo-sync/github-sync@v2
        if: env.TOCURRENT == 'true'
        with:
          source_repo: "https://github.com/${{ env.SOURCE_OWNER }}/${{ matrix.list }}.git"
          source_branch: "master"
          destination_branch: "master"
          sync_tags: "false"
          github_token: ${{ secrets.PAT }}
          
      - name: git-sync-remote-branch-Zerotier-One
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && matrix.list == 'ZeroTierOne'
        with:
          source_repo: "${{ env.SOURCE_OWNER }}/${{ matrix.list }}"
          source_branch: "refs/remotes/source/*"
          #source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          destination_branch: "refs/heads/*"
          #destination_branch: "refs/tags/*"          
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: git-sync-remote-tags-Zerotier-One
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && env.SYNCTAGS == 'true' && matrix.list == 'ZeroTierOne'
        with:
          source_repo: "${{ env.SOURCE_OWNER }}/${{ matrix.list }}"
          #source_branch: "refs/remotes/source/*"
          source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          #destination_branch: "refs/heads/*"
          destination_branch: "refs/tags/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`

      - name: git-sync-remote-branch-Zerotier-One-mkmoonworld
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && matrix.list == 'ZeroTierOne'
        with:
          source_repo: "Ausaci/ZeroTierOne-Official"
          source_branch: "mkmoonworld"
          #source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          destination_branch: "mkmoonworld"
          #destination_branch: "refs/tags/*"          
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: git-sync-remote-tags-Zerotier-One-mkmoonworld
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && env.SYNCTAGS == 'true' && matrix.list == 'ZeroTierOne'
        with:
          source_repo: "Ausaci/ZeroTierOne-Official"
          #source_branch: "refs/remotes/source/*"
          source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          #destination_branch: "refs/heads/*"
          destination_branch: "refs/tags/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`

      - name: git-sync-remote-branch-Zerotier-One-kaaass-mkmoonworld
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && matrix.list == 'ZeroTierOne' && env.KAAASS == 'true'
        with:
          source_repo: "kaaass/ZeroTierOne"
          source_branch: "master"
          #source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          destination_branch: "mkmoonworld-kaaass"
          #destination_branch: "refs/tags/*"          
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: git-sync-remote-tags-Zerotier-One-kaaass-mkmoonworld
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && env.SYNCTAGS == 'true' && matrix.list == 'ZeroTierOne' && env.KAAASS == 'true'
        with:
          source_repo: "kaaass/ZeroTierOne"
          #source_branch: "refs/remotes/source/*"
          source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ matrix.list }}"
          #destination_branch: "refs/heads/*"
          destination_branch: "refs/tags/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`


      - name: git-sync-remote-branch
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && matrix.list != 'ZeroTierOne'
        with:
          source_repo: "${{ env.SOURCE_OWNER }}/${{ matrix.list }}"
          source_branch: "refs/remotes/source/*"
          #source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ env.SOURCE_OWNER }}_${{ matrix.list }}"
          destination_branch: "refs/heads/*"
          #destination_branch: "refs/tags/*"          
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: git-sync-remote-tags
        uses: wei/git-sync@v3.0.0
        if: env.TOREMOTE == 'true' && env.SYNCTAGS == 'true' && matrix.list != 'ZeroTierOne'
        with:
          source_repo: "${{ env.SOURCE_OWNER }}/${{ matrix.list }}"
          #source_branch: "refs/remotes/source/*"
          source_branch: "refs/tags/*"
          destination_repo: "${{ env.DEST_OWNER }}/${{ env.SOURCE_OWNER }}_${{ matrix.list }}"
          #destination_branch: "refs/heads/*"
          destination_branch: "refs/tags/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          #source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY_SOURCE_OWNER }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v1.2.3
        with:          
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 30
          keep_minimum_runs: 1
          
