# File: .github/workflows/repo-sync.yml
# Need add secrets.PAT

name: repo-sync-template
on:
  workflow_dispatch:
 # schedule:
   # - cron: '0 1 * * 1'
    # UTC时区，比我们东八区早，上面示例为：每周一9点。
    
env:
  TZ: Asia/Shanghai
  TOCURRENT: false
  TOREMOTE: ture
  
jobs:
  repo-sync:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:  
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: repo-sync-current      
        uses: repo-sync/github-sync@v2
        if: env.TOCURRENT == 'true'
        with:
          source_repo: "https://github.com/template/template.git"
          source_branch: "master"
          destination_branch: "master"
          sync_tags: "false"
          github_token: ${{ secrets.PAT }}
          
      - name: git-sync-remote
        uses: wei/git-sync@v3
        if: env.TOREMOTE == 'true'
        with:
          source_repo: "unifreq/openwrt_packit"
          source_branch: "refs/remotes/source/*"
          source_branch: "refs/tags/*"
          destination_repo: "Namestars/openwrt_packit"
          destination_branch: "refs/heads/*"
          destination_branch: "refs/tags/*"          
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} # optional
          source_ssh_private_key: ${{ secrets.SOURCE_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          destination_ssh_private_key: ${{ secrets.DESTINATION_SSH_PRIVATE_KEY }} # optional, will override `SSH_PRIVATE_KEY`
          
