# Ausaci CopyRight

name: Update Archives Release

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'

#  schedule:
#    - cron: 30 23 * * *
#  release:
#    types: published
#  watch:
#    types: started

env:
  TZ: Asia/Shanghai
  CURL_COMMAND: 'curl -H "Authorization: token ${{ secrets.SOURCE_TOKEN_AUSACI }}" -H "Accept: application/vnd.github.v3+json"'
  CURL_DOWNLOAD_COMMAND: 'curl -vLJO -H "Authorization: token ${{ secrets.SOURCE_TOKEN_AUSACI }}" -H "Accept: application/octet-stream"'
  SOURCE_REPO: Ausaci/Archives
  OWNER: Namestars
  REPO: Archives
  TAG_BRANCH: master
  TAG_NAME: your tag name
  RELEASE_NAME: your release name

jobs:
  update-release:
    runs-on: ubuntu-latest
    if: github.event.sender.id == '54447830' || github.event.repository.owner.id == github.event.sender.id
    
    name: Update ${{ matrix.release_name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - { release_name: "Repos", tag_name: "20210521_IPv6", url: "https://api.github.com/repos/Ausaci/Archives/releases/43324999" }
          - { release_name: "NerdVPS", tag_name: "20210518_NerdVPS", url: "https://api.github.com/repos/Ausaci/Archives/releases/43150276" }
          - { release_name: "Config", tag_name: "Config", url: "https://api.github.com/repos/Ausaci/Archives/releases/39372406" }
          - { release_name: "ddbr_files", tag_name: "ddbr", url: "https://api.github.com/repos/Ausaci/Archives/releases/39372711" }
          - { release_name: "Tools", tag_name: "Tools", url: "https://api.github.com/repos/Ausaci/Archives/releases/39372443" }
          - { release_name: "Openwrt_HP_Printer", tag_name: "HP_Printer", url: "https://api.github.com/repos/Ausaci/Archives/releases/39372478" }
        
    steps:
      
    - name: Checkout
      uses: actions/checkout@master

    - name: Initial environments
      run: |
        sudo mkdir -p /workdir/downloads/${{ matrix.release_name }}
        sudo chmod 777 /workdir/downloads
        sudo chmod 777 /workdir/downloads/${{ matrix.release_name }}
        cd /workdir/downloads/${{ matrix.release_name }}
        echo "FILES=$PWD" >> $GITHUB_ENV
        echo -e $(${{ env.CURL_COMMAND }} -fsSL ${{ matrix.url }} | grep body | cut -d '"' -f 4) | sudo tee /workdir/BODY_${{ matrix.release_name }}.md
        echo "::set-output name=status::success"
        
    - name: Download all Release
      id: download
      uses: cb80/dlassets@latest
      with:
        tag: ${{ matrix.tag_name }}
        repo: ${{ env.SOURCE_REPO }}
        to: /workdir/downloads/${{ matrix.release_name }}
        token: ${{ secrets.SOURCE_TOKEN_AUSACI }}
        
    - name: SSH connection to Actions
      uses: P3TERX/ssh2actions@v1.0.0
      if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh  != 'false') || contains(github.event.action, 'ssh')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        
    - name: Upload to release
      id: release
      uses: ncipollo/release-action@v1
      with:
        name: ${{ matrix.release_name }}
        allowUpdates: true
        owner: ${{ env.OWNER }}
        repo: ${{ env.REPO }}
        tag: ${{ matrix.tag_name }}
        commit: ${{ env.TAG_BRANCH }}
        token: ${{ secrets.PAT }}
        #body: Body
        bodyFile: /workdir/BODY_${{ matrix.release_name }}.md
        artifacts: /workdir/downloads/${{ matrix.release_name }}/*
